# add stages here 
stages:
  stage_one:
    cmd: python src/stage_01.py
    deps:
    - src/stage_01.py
    outs:
    - output/output.txt

  stage_two:
    cmd: python src/stage_02.py
    deps:
    - src/stage_02.py
    - output/output.txt
    outs:
    - output/output2.txt
  stage_three:
    cmd: python src/stage_03.py
    deps:
    - src/stage_03.py
    - output/output.txt
